export enum DomainExceptionCode {
  DEFAULT_DOMAIN_EXCEPTION = "DEFAULT_DOMAIN_EXCEPTION",
  LOAN_AMOUNT_REQUIRED = "LOAN_AMOUNT_REQUIRED",
  LOAN_USER_GUID_REQUIRED = "LOAN_USER_GUID_REQUIRED",
  LOAN_USER_NOT_FOUND = "LOAN_USER_NOT_FOUND",
  LOAN_AVAL_REQUIRED = "LOAN_AVAL_REQUIRED",
  LOAN_AVAL_NOT_FOUND = "LOAN_AVAL_NOT_FOUND",
  LOAN_CURRENT_RATE_REQUIRED = "LOAN_CURRENT_RATE",
  LOAN_STATE_REQUIRED = "LOAN_STATE_REQUIRED",
  LOAN_PAY_DAY_REQUIRED = "LOAN_PAY_DAY_REQUIRED",
  LOAN_BALANCE_REQUIRED = "LOAN_BALANCE_REQUIRED",
  LOAN_NOT_FOUND = "LOAN_NOT_FOUND",
  LOAN_SAME_GUID = "LOAN_SAME_GUID",
}
